Uses 1.653 as baseline therwise we can't run the plugin locally via `hpi:run` because we get NoSuchMethodError: jenkins.model.Jenkins.getInstanceOrNull()